---
title: "Limitations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Limitations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Software

As of now, eyeScrollR was only tested with .csv outputs from the iMotions
software. However, as long as the user manages to convert its own .csv file
to the same format, this package should be perfectly able to accomplish its task.

Native support for other software is planned, but not guaranteed at the moment.

# Browser-generated events

iMotions allows users to record websites instead of screens. This gives access
to more user-generated events through browser messages, and should theoretically
give more accurate scroll corrections.

However, browsers ran through iMotions does **not** include plugins and custom
settings (much like running in private navigation), which can be indispensable
for most. as such, even though eyeScrollR functions can be run on data using the
website recordings, it will not use the browser-generated events. It is
recommended to simply use the whole screen recording procedure.

# Keypresses and scrollbars

eyeScrollR mainly works by catching the MOUSEWHEEL key event, and correcting the
fixation coordinates accordingly. However, the mouse wheel is not the only way
to scroll up/down on a website, and the researcher should ALWAYS make sure that
participants did not, for instance, press a space bar or the page down key
(when outside of an input field). These events are **not** handled by the
package, and will therefore not be considered at all.

Similarly, participants should also be discouraged from using the side scrollbar
(if it could not be completely disabled), for the same reason.

Finally, some websites have scrollbars inside subcomponents of their webpage. In
this situation, using the mousewheel while pointing at this area will scroll
down the subcomponent, but not the whole page. However, eyeScrollR will still
interpret the event as a scroll down for the entire page. There is, however, no
other choices than to either refrain from using this package in such settings,
or manually remove these scrolling events from the .csv file.

Please acknowledge that eyeScrollR is still very new. As a consequence, it is
more than highly recommended that any user checks if fixations correspond to
individual recordings of participants before publishing any data.
